config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'

  get 'pages/um_bokatidindi'
  get 'pages/prentutgafa'
  get 'pages/privacy_policy'
  get 'pages/open_data'

  get 'baekur/', to: 'books#index'
  get 'baekur/sida/:page', to: 'books#index'

  get 'baekur/flokkur/:category', to: 'books#index', as: 'category'
  get 'baekur/flokkur/:category/sida/:page', to: 'books#index'

  get 'baekur/utgefandi/:publisher', to: 'books#index', as: 'publisher'
  get 'baekur/utgefandi/:publisher/sida/:page', to: 'books#index'

  get 'baekur/hofundur/:author', to: 'books#index', as: 'author'
  get 'baekur/hofundur/:author/sida/:page', to: 'books#index'

  get 'baekur/leit/:search', to: 'books#index'

  get 'bok/:slug', to: 'books#show', as: 'book'

  get 'xml_feeds/editions_for_print/:id', to: 'xml_feeds#edition_for_print'
  get 'xml_feeds/editions_for_print/current', to: 'xml_feeds#edition_for_print'

  get 'argangar', to: 'editions#index'
  get 'argangar/:id', to: 'editions#show'

  get 'manifest.json', to: 'welcome#manifest'
end

app/views/indexes/authors.html.erb
<main role="main">

  <div class="container-fluid">

    <div class="row mx-2">

      <div class="col-12">

      <h2>Höfundar</h2>

      </div>

      <% @authors_by_first_initial.each_key do |initial| %>
      <div class="col-12 col-lg-3">
        <h3><%= initial %></h3>
        <ul>
          <% @authors_by_first_initial[initial].each do |a| %>
          <li><%= link_to a.name, author_path(a.slug) %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

    </div>

  </div>

</main>

app/views/indexes/publishers.html.erb
<main role="main">

  <div class="container-fluid">

    <div class="row mx-2">

      <div class="col-12">

        <h2>Útgefendur</h2>

      </div>

      <% @publishers_by_first_initial.each_key do |initial| %>
      <div class="col-12 col-lg-3">
        <h3><%= initial %></h3>
        <ul>
          <% @publishers_by_first_initial[initial].each do |p| %>
          <li><%= link_to p.name, publisher_path(p.slug) %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

    </div>

  </div>

</main>