config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'

  get 'pages/um_bokatidindi'
  get 'pages/prentutgafa'
  get 'pages/privacy_policy'
  get 'pages/open_data'

  get 'baekur/', to: 'books#index'
  get 'baekur/sida/:page', to: 'books#index'

  get 'baekur/flokkur/:category', to: 'books#index', as: 'category'
  get 'baekur/flokkur/:category/sida/:page', to: 'books#index'

  get 'baekur/utgefandi/:publisher', to: 'books#index', as: 'publisher'
  get 'baekur/utgefandi/:publisher/sida/:page', to: 'books#index'

  get 'baekur/hofundur/:author', to: 'books#index', as: 'author'
  get 'baekur/hofundur/:author/sida/:page', to: 'books#index'

  get 'baekur/leit/:search', to: 'books#index'

  get 'bok/:slug', to: 'books#show', as: 'book'

  get 'xml_feeds/editions_for_print/:id', to: 'xml_feeds#edition_for_print'
  get 'xml_feeds/editions_for_print/current', to: 'xml_feeds#edition_for_print'

  get 'argangar', to: 'editions#index'
  get 'argangar/:id', to: 'editions#show'

  get 'manifest.json', to: 'welcome#manifest'
end

app/views/pages/open_data.html.erb
<% content_for :meta do %>
  <title>Bókatíðindi - Opin gögn</title>
<% end %>

<main class="page pb-5">

<div class="container-xl">

<div class="row">

  <div class="col-12 px-5 pb-3 pt-5 pb-xl-3">
    <h1><%= @page_content[:title] if @page_content %></h1>
  </div>

  <div class="col-12 page-container px-5 py-xl-5 mb-xl-5">
    <%= markdown(@page_content.body) if @page_content %>
  </div>
  <div class="col-12 page-container p-5 mb-5">
    <h2 class="mb-3">Vefslóðir</h2>
    <table class="table">
      <thead>
        <tr>
          <th span="col">Árgangur</th>
          <th span="col">Vefslóð</th>
        </tr>
      </thead>
      <tbody>
        <tr scope="row">
          <td>Núverandi árgangur</td>
          <td><a title="Vefslóð á JSON-tendapunkt núverandi árgangs" href="<%= argangar_url %>/current.json"><%= argangar_url %>/current.json</a></td>
        </tr>
        <% Edition.all.each do |edition| %>
        <% next if edition.books.count.zero? %>
        <tr scope="row">
          <td><%= edition.title %></td>
          <td><a title="Vefslóð á JSON-endapunkt árgangsins" href="<%= argangar_url %>/<%= edition.id %>.json"><%= argangar_url %>/<%= edition.id %>.json</a></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

</div>

</main>

app/views/pages/prentutgafa.erb
<% content_for :meta do %>
  <title><%= @page_content[:title] if @page_content %></title>

  <% if @current_edition&.cover_image&.attached? %>
  <%= tag 'meta', property: 'og:image', content: @current_edition.cover_image_url %>
  <% end %>
  <%= tag 'meta', property: 'og:site_name', content: 'Bókatíðindi' %>
  <%= tag 'meta', property: 'og:title', content: 'Um Bókatíðindi' %>
  <%= tag 'meta', property: 'og:locale', content: 'is_IS' %>
  <%= tag 'meta', property: 'fb:app_id', content: '286582403328194' %>

  <%= tag 'meta', name: 'twitter:card', content: 'summary' %>
  <%= tag 'meta', name: 'twitter:title', content: 'Um Bókatíðindi' %>
  <% if @current_edition&.cover_image&.attached? %>
  <%= tag 'meta', name: 'twitter:image', content: @current_edition.cover_image_url %>
  <% end %>
<% end %>

<main class="page">

  <div class="container-xl">

    <div class="row pb-5">
      <div class="col-12 px-5 pb-3 pt-5 pb-xl-3">
        <h1><%= @page_content[:title] if @page_content %></h1>
      </div>
      <div class="page-container prentutgafa-container col-12 px-5 py-xl-5">
        <%= markdown(@page_content.body) if @page_content %>
      </div>
    </div>
  </div>
</main>

app/views/pages/privacy_policy.html.erb
<% content_for :meta do %>
  <title>Bókatíðindi - Köku- og friðhelgisstefna</title>
<% end %>

<main class="page pb-5">

<div class="container-xl">

<div class="row">

  <div class="col-12 px-5 pb-3 pt-5 pb-xl-3">
    <h1><%= @page_content[:title] if @page_content %></h1>
  </div>

  <div class="col-12 page-container col-12 px-5 py-xl-5">
    <%= markdown(@page_content.body) if @page_content %>
  </div>

</div>

</div>

</main>

app/views/pages/um_bokatidindi.html.erb
<% content_for :meta do %>
  <title>Um Bókatíðindi</title>

  <% if @current_edition&.cover_image&.attached? %>
  <%= tag 'meta', property: 'og:image', content: @current_edition.cover_image_url %>
  <% end %>
  <%= tag 'meta', property: 'og:site_name', content: 'Bókatíðindi' %>
  <%= tag 'meta', property: 'og:title', content: 'Um Bókatíðindi' %>
  <%= tag 'meta', property: 'og:locale', content: 'is_IS' %>
  <%= tag 'meta', property: 'fb:app_id', content: '286582403328194' %>

  <%= tag 'meta', name: 'twitter:card', content: 'summary' %>
  <%= tag 'meta', name: 'twitter:title', content: 'Um Bókatíðindi' %>
  <% if @current_edition&.cover_image&.attached? %>
  <%= tag 'meta', name: 'twitter:image', content: @current_edition.cover_image_url %>
  <% end %>
<% end %>

<main class="page">

  <div class="container-xl">

    <div class="row pb-5">
      <div class="col-12 px-5 pb-3 pt-5 pb-xl-3">
        <h1><%= @page_content[:title] if @page_content %></h1>
      </div>
      <div class="page-container col-12 px-5 py-xl-5">
        <%= markdown(@page_content.body) if @page_content %>
      </div>
    </div>
  </div>
</main>